version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: daze
      POSTGRES_PASSWORD: devps123
      POSTGRES_DB: bannerservice
    ports:
      - "5432:5432"

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /docs/swagger.yaml
    volumes:
      - ./docs/swagger.yaml:/docs/swagger.yaml
    ports:
      - "8081:8080"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"