version: '3.8'
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      pgsql:
        condition: service_healthy

  pgsql:
    image: postgres:13
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: ${SWAGGER_JSON}
    volumes:
      - ./docs/swagger.yaml:/docs/swagger.yaml
    ports:
      - "${SWAGGER_UI_PORT}:8080"

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
